In [2]:
"""
    Created on 25 April 2026

    Author: Salma Ibrahim Ed-Desouki
"""

import pandas as pd

df_cust_info = pd.read_csv("D:\\Projects\\DataWarehouse\\sql-dw-project\\datasets\\source_crm\\cust_info.csv");

df_cust_info

,cst_id,cst_key,cst_firstname,cst_lastname,cst_marital_status,cst_gndr,cst_create_date
0,11000.0,AW00011000,Jon,Yang,M,M,2025-10-06
1,11001.0,AW00011001,Eugene,Huang,S,M,2025-10-06
2,11002.0,AW00011002,Ruben,Torres,M,M,2025-10-06
3,11003.0,AW00011003,Christy,Zhu,S,F,2025-10-06
4,11004.0,AW00011004,Elizabeth,Johnson,S,F,2025-10-06
...,...,...,...,...,...,...,...
18489,29482.0,AW00029482,Clayton,Zhang,M,NaN,2026-01-25
18490,29483.0,AW00029483,NaN,Navarro,NaN,NaN,2026-01-25
18491,29483.0,AW00029483,Marc,Navarro,M,NaN,2026-01-27
18492,NaN,13451235,NaN,NaN,NaN,NaN,NaN
18493,NaN,A01Ass,NaN,NaN,NaN,NaN,NaN

In [14]:
# df_cust_info.info() # 18494 
#df_cust_info.describe(include="all")
df_csv = df_cust_info
df_csv["comp_key"] = df_csv["cst_key"].astype(str) + "_" + pd.to_datetime(df_csv["cst_create_date"]).dt.strftime("%Y-%m-%d").fillna("1900-01-01")

df_csv
# pd.Timestamp("1900-01-01")

,cst_id,cst_key,cst_firstname,cst_lastname,cst_marital_status,cst_gndr,cst_create_date,comp_key
0,11000.0,AW00011000,Jon,Yang,M,M,2025-10-06,AW00011000_2025-10-06
1,11001.0,AW00011001,Eugene,Huang,S,M,2025-10-06,AW00011001_2025-10-06
2,11002.0,AW00011002,Ruben,Torres,M,M,2025-10-06,AW00011002_2025-10-06
3,11003.0,AW00011003,Christy,Zhu,S,F,2025-10-06,AW00011003_2025-10-06
4,11004.0,AW00011004,Elizabeth,Johnson,S,F,2025-10-06,AW00011004_2025-10-06
...,...,...,...,...,...,...,...,...
18489,29482.0,AW00029482,Clayton,Zhang,M,NaN,2026-01-25,AW00029482_2026-01-25
18490,29483.0,AW00029483,NaN,Navarro,NaN,NaN,2026-01-25,AW00029483_2026-01-25
18491,29483.0,AW00029483,Marc,Navarro,M,NaN,2026-01-27,AW00029483_2026-01-27
18492,NaN,13451235,NaN,NaN,NaN,NaN,NaN,13451235_1900-01-01
18493,NaN,A01Ass,NaN,NaN,NaN,NaN,NaN,A01Ass_1900-01-01

In [11]:
df_prd_info = pd.read_csv("D:\\Projects\\DataWarehouse\\sql-dw-project\\datasets\\source_crm\\prd_info.csv")
df_prd_info

,prd_id,prd_key,prd_nm,prd_cost,prd_line,prd_start_dt,prd_end_dt
0,210,CO-RF-FR-R92B-58,HL Road Frame - Black- 58,NaN,R,2003-07-01,NaN
1,211,CO-RF-FR-R92R-58,HL Road Frame - Red- 58,NaN,R,2003-07-01,NaN
2,212,AC-HE-HL-U509-R,Sport-100 Helmet- Red,12.0,S,2011-07-01,2007-12-28
3,213,AC-HE-HL-U509-R,Sport-100 Helmet- Red,14.0,S,2012-07-01,2008-12-27
4,214,AC-HE-HL-U509-R,Sport-100 Helmet- Red,13.0,S,2013-07-01,NaN
...,...,...,...,...,...,...,...
392,602,CO-BB-BB-8107,ML Bottom Bracket,45.0,NaN,2013-07-01,NaN
393,603,CO-BB-BB-9108,HL Bottom Bracket,54.0,NaN,2013-07-01,NaN
394,604,BI-RB-BK-R19B-44,Road-750 Black- 44,344.0,R,2013-07-01,NaN
395,605,BI-RB-BK-R19B-48,Road-750 Black- 48,344.0,R,2013-07-01,NaN
396,606,BI-RB-BK-R19B-52,Road-750 Black- 52,344.0,R,2013-07-01,NaN

In [ ]:
df_prd_info.info() #397

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   prd_id        397 non-null    int64
 1   prd_key       397 non-null    object
 2   prd_nm        397 non-null    object
 3   prd_cost      395 non-null    float64
 4   prd_line      380 non-null    object
 5   prd_start_dt  397 non-null    object
 6   prd_end_dt    200 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 21.8+ KB

In [ ]:
df_sales_details = pd.read_csv("D:\\Projects\\DataWarehouse\\sql-dw-project\\datasets\\source_crm\\sales_details.csv")
df_sales_details

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price
0,SO43697,BK-R93R-62,21768,20101229,20110105,20110110,3578.0,1,3578.0
1,SO43698,BK-M82S-44,28389,20101229,20110105,20110110,3400.0,1,3400.0
2,SO43699,BK-M82S-44,25863,20101229,20110105,20110110,3400.0,1,3400.0
3,SO43700,BK-R50B-62,14501,20101229,20110105,20110110,699.0,1,699.0
4,SO43701,BK-M82S-44,11003,20101229,20110105,20110110,3400.0,1,3400.0
...,...,...,...,...,...,...,...,...,...
60393,SO75122,FE-6654,15868,20140128,20140204,20140209,22.0,1,22.0
60394,SO75122,CA-1098,15868,20140128,20140204,20140209,9.0,1,9.0
60395,SO75123,FE-6654,18759,20140128,20140204,20140209,22.0,1,22.0
60396,SO75123,ST-1401,18759,20140128,20140204,20140209,159.0,1,159.0
60397,SO75123,CA-1098,18759,20140128,20140204,20140209,9.0,1,9.0

In [ ]:
df_sales_details.info() #60398

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60398 entries, 0 to 60397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sls_ord_num   60398 non-null  object
 1   sls_prd_key   60398 non-null  object
 2   sls_cust_id   60398 non-null  int64
 3   sls_order_dt  60398 non-null  int64
 4   sls_ship_dt   60398 non-null  int64
 5   sls_due_dt    60398 non-null  int64
 6   sls_sales     60390 non-null  float64
 7   sls_quantity  60398 non-null  int64
 8   sls_price     60391 non-null  float64
dtypes: float64(2), int64(5), object(2)
memory usage: 4.1+ MB

In [ ]:
df_cust_az12 = pd.read_csv("D:\\Projects\\DataWarehouse\\sql-dw-project\\datasets\\source_erp\\cust_az12.csv")
df_cust_az12 # 18484

                 CID       BDATE     GEN
0      NASAW00011000  1971-10-06    Male
1      NASAW00011001  1976-05-10    Male
2      NASAW00011002  1971-02-09    Male
3      NASAW00011003  1973-08-14  Female
4      NASAW00011004  1979-08-05  Female
...              ...         ...     ...
18479     AW00029479  1969-06-30     NaN
18480     AW00029480  1977-05-06     NaN
18481     AW00029481  1965-07-04     NaN
18482     AW00029482  1964-09-01     NaN
18483     AW00029483  1965-06-06     NaN

[18484 rows x 3 columns]

In [ ]:
df_loc_a101 = pd.read_csv("D:\\Projects\\DataWarehouse\\sql-dw-project\\datasets\\source_erp\\loc_a101.csv")
df_loc_a101 #18484

               CID           CNTRY
0      AW-00011000       Australia
1      AW-00011001       Australia
2      AW-00011002       Australia
3      AW-00011003       Australia
4      AW-00011004       Australia
...            ...             ...
18479  AW-00029479          France
18480  AW-00029480  United Kingdom
18481  AW-00029481         Germany
18482  AW-00029482          France
18483  AW-00029483          France

[18484 rows x 2 columns]

In [ ]:
df_px_cat_g1v2 = pd.read_csv("D:\\Projects\\DataWarehouse\\sql-dw-project\\datasets\\source_erp\\px_cat_g1v2.csv")
df_px_cat_g1v2.info()
#37

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           37 non-null     object
 1   CAT          37 non-null     object
 2   SUBCAT       37 non-null     object
 3   MAINTENANCE  37 non-null     object
dtypes: object(4)
memory usage: 1.3+ KB

In [ ]:
import pyodbc
pyodbc.drivers()
# ODBC Driver 18 for SQL Server
# sql express

['SQL Server',
 'Oracle in OraDB21Home1',
 'SQL Server Native Client 11.0',
 'ODBC Driver 13 for SQL Server',
 'SQL Server Native Client RDA 11.0',
 'ODBC Driver 17 for SQL Server',
 'ODBC Driver 18 for SQL Server']